// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// FARIMAforecastAR
arma::vec FARIMAforecastAR(arma::vec& obs, const arma::rowvec& ar_inf, const double meanObs, const int m);
RcppExport SEXP _esemifar_FARIMAforecastAR(SEXP obsSEXP, SEXP ar_infSEXP, SEXP meanObsSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type obs(obsSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec& >::type ar_inf(ar_infSEXP);
    Rcpp::traits::input_parameter< const double >::type meanObs(meanObsSEXP);
    Rcpp::traits::input_parameter< const int >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(FARIMAforecastAR(obs, ar_inf, meanObs, m));
    return rcpp_result_gen;
END_RCPP
}
// FARIMAfutureObs
arma::vec FARIMAfutureObs(arma::vec& obs, const arma::rowvec& ar_inf, const arma::vec& et, const double meanObs);
RcppExport SEXP _esemifar_FARIMAfutureObs(SEXP obsSEXP, SEXP ar_infSEXP, SEXP etSEXP, SEXP meanObsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type obs(obsSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec& >::type ar_inf(ar_infSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type et(etSEXP);
    Rcpp::traits::input_parameter< const double >::type meanObs(meanObsSEXP);
    rcpp_result_gen = Rcpp::wrap(FARIMAfutureObs(obs, ar_inf, et, meanObs));
    return rcpp_result_gen;
END_RCPP
}
// ARinftySHORT
arma::vec ARinftySHORT(const arma::vec& ar, const arma::rowvec& ma, const int max_i);
RcppExport SEXP _esemifar_ARinftySHORT(SEXP arSEXP, SEXP maSEXP, SEXP max_iSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type ar(arSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec& >::type ma(maSEXP);
    Rcpp::traits::input_parameter< const int >::type max_i(max_iSEXP);
    rcpp_result_gen = Rcpp::wrap(ARinftySHORT(ar, ma, max_i));
    return rcpp_result_gen;
END_RCPP
}
// MAinftySHORT
arma::vec MAinftySHORT(const arma::rowvec& ar, const arma::vec& ma, const int max_i);
RcppExport SEXP _esemifar_MAinftySHORT(SEXP arSEXP, SEXP maSEXP, SEXP max_iSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::rowvec& >::type ar(arSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type ma(maSEXP);
    Rcpp::traits::input_parameter< const int >::type max_i(max_iSEXP);
    rcpp_result_gen = Rcpp::wrap(MAinftySHORT(ar, ma, max_i));
    return rcpp_result_gen;
END_RCPP
}
// ARinftyLONG
arma::vec ARinftyLONG(arma::rowvec& ar, const arma::vec& d_coef);
RcppExport SEXP _esemifar_ARinftyLONG(SEXP arSEXP, SEXP d_coefSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::rowvec& >::type ar(arSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type d_coef(d_coefSEXP);
    rcpp_result_gen = Rcpp::wrap(ARinftyLONG(ar, d_coef));
    return rcpp_result_gen;
END_RCPP
}
// MAinftyLONG
arma::rowvec MAinftyLONG(arma::vec& ma, const arma::vec& d_coef);
RcppExport SEXP _esemifar_MAinftyLONG(SEXP maSEXP, SEXP d_coefSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type ma(maSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type d_coef(d_coefSEXP);
    rcpp_result_gen = Rcpp::wrap(MAinftyLONG(ma, d_coef));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_esemifar_FARIMAforecastAR", (DL_FUNC) &_esemifar_FARIMAforecastAR, 4},
    {"_esemifar_FARIMAfutureObs", (DL_FUNC) &_esemifar_FARIMAfutureObs, 4},
    {"_esemifar_ARinftySHORT", (DL_FUNC) &_esemifar_ARinftySHORT, 3},
    {"_esemifar_MAinftySHORT", (DL_FUNC) &_esemifar_MAinftySHORT, 3},
    {"_esemifar_ARinftyLONG", (DL_FUNC) &_esemifar_ARinftyLONG, 2},
    {"_esemifar_MAinftyLONG", (DL_FUNC) &_esemifar_MAinftyLONG, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_esemifar(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
