# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

FARIMAforecastAR <- function(obs, ar_inf, meanObs, m) {
    .Call('_esemifar_FARIMAforecastAR', PACKAGE = 'esemifar', obs, ar_inf, meanObs, m)
}

FARIMAfutureObs <- function(obs, ar_inf, et, meanObs) {
    .Call('_esemifar_FARIMAfutureObs', PACKAGE = 'esemifar', obs, ar_inf, et, meanObs)
}

ARinftySHORT <- function(ar, ma, max_i) {
    .Call('_esemifar_ARinftySHORT', PACKAGE = 'esemifar', ar, ma, max_i)
}

MAinftySHORT <- function(ar, ma, max_i) {
    .Call('_esemifar_MAinftySHORT', PACKAGE = 'esemifar', ar, ma, max_i)
}

ARinftyLONG <- function(ar, d_coef) {
    .Call('_esemifar_ARinftyLONG', PACKAGE = 'esemifar', ar, d_coef)
}

MAinftyLONG <- function(ma, d_coef) {
    .Call('_esemifar_MAinftyLONG', PACKAGE = 'esemifar', ma, d_coef)
}

